pipeline {
  agent none
  stages {
    stage('Back-end Build') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end Build') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}

// this way in every stage of backend and frontend you can use different agent having different dependencies even different languages
